# AUTOGENERATED CONFIG - NOUGAT V3
SELECTION_METHOD="default"
SCREENSHOT_DIRECTORY="$HOME/screenshots"
SCREENCAST_DIRECTORY="$HOME/recordings"
ORGANIZATION_POLICY='${year}-${month}-${day}T${hour}:${minute}:${second}'
